version: '3'
services:
  remix-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/remix-jokes/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
